adventure_works_dbt_modeling:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SF_DB_ACCOUNT') }}"
      user: "{{ env_var('DBT_SF_DEV_USER') }}"
      password: "{{ env_var('DBT_SF_DEV_PASSWORD') }}"
      role: "{{ env_var('DBT_SF_DEV_ROLE') }}"
      database: "{{ env_var('DBT_SF_DEV_DATABASE') }}"
      warehouse: "{{ env_var('DBT_SF_DEV_WAREHOUSE') }}"
      schema: "dev"
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: "{{ env_var('DBT_SF_DB_ACCOUNT') }}"
      user: "{{ env_var('DBT_SF_PROD_USER') }}" 
      password: "{{ env_var('DBT_SF_PROD_PASSWORD') }}" 
      role: "{{ env_var('DBT_SF_PROD_ROLE') }}"
      database: "{{ env_var('DBT_SF_PROD_DATABASE') }}"  
      warehouse: "{{ env_var('DBT_SF_PROD_WAREHOUSE') }}" 
      schema: "{{ env_var('DBT_SF_PROD_SCHEMA') }}"
      client_session_keep_alive: False
