version: 1
default_environment: dev
project_id: 33577f17-4c64-4c79-8ce7-f7119315663c
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      batch_size: 100000
      database: $TAP_POSTGRES_DATABASE
      host: $TAP_POSTGRES_HOST
      port: $TAP_POSTGRES_PORT
      user: $TAP_POSTGRES_USER
      password: $TAP_POSTGRES_PASSWORD
    select:
    - 'person-stateprovince.*'
    - 'sales-countryregioncurrency.*'
    - 'sales-creditcard.*'
    - 'sales-currency.*'
    - 'sales-currencyrate.*'
    - 'sales-customer.*'
    - 'sales-personcreditcard.*'
    - 'sales-salesorderdetail.*'
    - 'sales-salesorderheader.*'
    - 'sales-salesorderheadersalesreason.*'
    - 'sales-salesperson.*'
    - 'sales-salespersonquotahistory.*'
    - 'sales-salesreason.*'
    - 'sales-salestaxrate.*'
    - 'sales-salesterritory.*'
    - 'sales-salesterritoryhistory.*'
    - 'sales-shoppingcartitem.*'
    - 'sales-specialoffer.*'
    - 'sales-specialofferproduct.*'
    - 'sales-store.*'
    - 'purchasing-productvendor.*'
    - 'purchasing-purchaseorderdetail.*'
    - 'purchasing-purchaseorderheader.*'
    - 'purchasing-shipmethod.*'
    - 'purchasing-vendor.*'
    - 'humanresources-department.*'
    - 'humanresources-employee.*'
    - 'humanresources-employeedepartmenthistory.*'
    - 'humanresources-employeepayhistory.*'
    - 'humanresources-jobcandidate.*'
    - 'humanresources-shift.*'
    - 'person-address.*'
    - 'person-addresstype.*'
    - 'person-businessentity.*'
    - 'person-businessentityaddress.*'
    - 'person-businessentitycontact.*'
    - 'person-contacttype.*'
    - 'person-countryregion.*'
    - 'person-emailaddress.*'
    - 'person-password.*'
    - 'person-person.*'
    - 'person-personphone.*'
    - 'person-phonenumbertype.*'
    - 'production-billofmaterials.*'
    - 'production-culture.*'
    - 'production-document.*'
    - 'production-illustration.*'
    - 'production-location.*'
    - 'production-product.*'
    - 'production-productcategory.*'
    - 'production-productdescription.*'
    - 'production-productdocument.*'
    - 'production-productinventory.*'
    - 'production-productlistpricehistory.*'
    - 'production-productmodel.*'
    - 'production-productmodelillustration.*'
    - 'production-productmodelproductdescriptionculture.*'
    - 'production-productphoto.*'
    - 'production-productproductphoto.*'
    - 'production-productreview.*'
    - 'production-productsubcategory.*'
    - 'production-scrapreason.*'
    - 'production-transactionhistory.*'
    - 'production-transactionhistoryarchive.*'
    - 'production-unitmeasure.*'
    - 'production-workorder.*'
    - 'production-workorderrouting.*'
    - 'production-productcosthistory.*'

  loaders:
  - name: target-snowflake
    variant: meltanolabs
    pip_url: meltanolabs-target-snowflake
    config:
      account: $TARGET_SNOWFLAKE_ACCOUNT
      database: $TARGET_SNOWFLAKE_DATABASE
      password: $TARGET_SNOWFLAKE_PASSWORD
      role: $TARGET_SNOWFLAKE_ROLE
      user: $TARGET_SNOWFLAKE_USER
      warehouse: $TARGET_SNOWFLAKE_WAREHOUSE
      batch_size_rows: 100000
      add_metadata_columns: true
      insecure_mode: true
      timestamp_column_name: _loaded_at
      #loading_method: replace  ou 'upsert'
